from Crypto.Cipher import AES
from Crypto.Hash import SHA256
import struct
from OpenSSL import rand

# Randomly generated by random.org
aes_key = "f28ea52a9a0e07e60683c0330a216d90".decode("hex")

# Generates a random number by making a number of the SHA-256
# hash for each of the extracted inputs
class SHA256Gen:
	name = "sha256"

	def __init__(self, input):
		self.input = input
		self.sha256 = SHA256.new()
		self.index = 0

	def get_rand(self):
		item = self.input[self.index]
		self.sha256.update(item)
		processed = self.sha256.hexdigest().decode("hex")
		self.input[self.index] = processed
		self.index = (self.index + 1) % len(self.input)
		return processed

# Generates a random number by applying the AES counter cipher to the
# sequence of extracted inputs
class AES128CtrGen:
	name = "aes128_ctr"

	def __init__(self, input):
		self.input = input
		self.counter = 0
		self.aes = AES.new(aes_key, AES.MODE_CTR, counter = lambda: struct.pack("Q", self.counter) + ("\x00" * 8))

	def get_rand(self):
		item = self.input[self.counter % len(self.input)]
		processed = self.aes.encrypt(item)
		self.counter = self.counter + 1 % len(self.input)
		return processed

# Generates random numbers by using the OpenSSL pseudorandom number
# generator with the entropy coming from the extracted randomness
class OpenSSLPRNGen:
	name = "openssl_prng"

	def __init__(self, input):
		self.prng = rand
		self.prng.seed("".join(input))

	def get_rand(self):
		self.prng.bytes(8)